# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'English3000' do
pod 'FMDB'

end

target 'English3000Tests' do

end

target 'English3000UITests' do

end

